sudo: required
language: cpp
dist: trusty

addons: 
  apt: 
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.7 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.6 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.5 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'ppa:presslabs/gitfs'
      
matrix: 
  include: 

    # sneak in 1 osx one so we can see it early
    - os: osx
      osx_image: xcode8.2
      env: BUILD_TYPE=Debug
    
    - env: CXX_COMPILER=g++-5         C_COMPILER=gcc-5      BUILD_TYPE=Debug     QT_VERSION=562 LLVM_VERSION=3.5 PACKAGES='g++-5 gcc-5'
    - env: CXX_COMPILER=g++-5         C_COMPILER=gcc-5      BUILD_TYPE=Debug     QT_VERSION=562 LLVM_VERSION=3.6 PACKAGES='g++-5 gcc-5'
    - env: CXX_COMPILER=g++-5         C_COMPILER=gcc-5      BUILD_TYPE=Debug     QT_VERSION=562 LLVM_VERSION=3.7 PACKAGES='g++-5 gcc-5'
    - env: CXX_COMPILER=g++-5         C_COMPILER=gcc-5      BUILD_TYPE=Release   QT_VERSION=571 LLVM_VERSION=3.8 PACKAGES='g++-5 gcc-5'
    - env: CXX_COMPILER=g++-6         C_COMPILER=gcc-6      BUILD_TYPE=Debug     QT_VERSION=58  LLVM_VERSION=3.9 PACKAGES='g++-6 gcc-6'
    - env: CXX_COMPILER=g++-6         C_COMPILER=gcc-6      BUILD_TYPE=Release   QT_VERSION=58  LLVM_VERSION=4.0 PACKAGES='g++-6 gcc-6'

    - os: osx
      osx_image: xcode8.2
      env: BUILD_TYPE=Release
    - os: osx
      osx_image: xcode8.1
      env: BUILD_TYPE=Debug
    - os: osx
      osx_image: xcode8.1
      env: BUILD_TYPE=Release
    - os: osx
      osx_image: xcode8
      env: BUILD_TYPE=Debug
    - os: osx
      osx_image: xcode8
      env: BUILD_TYPE=Release
    - os: osx
      osx_image: xcode7.3
      env: BUILD_TYPE=Debug
    - os: osx
      osx_image: xcode7.3
      env: BUILD_TYPE=Release
      
        
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/


install: 
  - ./.travis/install.sh

script:
  - ./.travis/build.sh
