sudo: required
language: cpp
dist: trusty

addons: 
  apt: 
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.7 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'ppa:beineri/opt-qt562-trusty'
      - sourceline: 'ppa:beineri/opt-qt571-trusty'
      
matrix: 
  include: 
  
    - env: CXX_COMPILER=g++-5         C_COMPILER=gcc-5      BUILD_TYPE=Debug     QT_VERSION=562 PACKAGES='g++5 gcc-5 python-pip'  TEST_COV=YES
    
    # sneak in 1 osx one so we can see it early
    - os: osx
      osx_image: xcode8.2
      env: BUILD_TYPE=Debug
    
    - env: CXX_COMPILER=g++-5         C_COMPILER=gcc-5      BUILD_TYPE=Release   QT_VERSION=562 PACKAGES='g++-5 gcc-5'
    - env: CXX_COMPILER=g++-6         C_COMPILER=gcc-6      BUILD_TYPE=Debug     QT_VERSION=562 PACKAGES='g++-6 gcc-6'
    - env: CXX_COMPILER=g++-6         C_COMPILER=gcc-6      BUILD_TYPE=Release   QT_VERSION=562 PACKAGES='g++-6 gcc-6'
    - env: CXX_COMPILER=clang++-3.7   C_COMPILER=clang-3.7  BUILD_TYPE=Debug     QT_VERSION=562 PACKAGES='clang-3.7'
    - env: CXX_COMPILER=clang++-3.7   C_COMPILER=clang-3.7  BUILD_TYPE=Release   QT_VERSION=562 PACKAGES='clang-3.7'
    - env: CXX_COMPILER=clang++-3.8   C_COMPILER=clang-3.8  BUILD_TYPE=Debug     QT_VERSION=562 PACKAGES='clang-3.8'
    - env: CXX_COMPILER=clang++-3.8   C_COMPILER=clang-3.8  BUILD_TYPE=Release   QT_VERSION=562 PACKAGES='clang-3.8'
    - env: CXX_COMPILER=clang++-3.9   C_COMPILER=clang-3.9  BUILD_TYPE=Debug     QT_VERSION=562 PACKAGES='clang-3.9'
    - env: CXX_COMPILER=clang++-3.9   C_COMPILER=clang-3.9  BUILD_TYPE=Release   QT_VERSION=562 PACKAGES='clang-3.9'
    - env: CXX_COMPILER=g++-5         C_COMPILER=gcc-5      BUILD_TYPE=Debug     QT_VERSION=571 PACKAGES='g++-5 gcc-5'
    - env: CXX_COMPILER=g++-5         C_COMPILER=gcc-5      BUILD_TYPE=Release   QT_VERSION=571 PACKAGES='g++-5 gcc-5'
    - env: CXX_COMPILER=g++-6         C_COMPILER=gcc-6      BUILD_TYPE=Debug     QT_VERSION=571 PACKAGES='g++-6 gcc-6'
    - env: CXX_COMPILER=g++-6         C_COMPILER=gcc-6      BUILD_TYPE=Release   QT_VERSION=571 PACKAGES='g++6 gcc-6'
    - env: CXX_COMPILER=clang++-3.7   C_COMPILER=clang-3.7  BUILD_TYPE=Debug     QT_VERSION=571 PACKAGES='clang-3.7'
    - env: CXX_COMPILER=clang++-3.7   C_COMPILER=clang-3.7  BUILD_TYPE=Release   QT_VERSION=571 PACKAGES='clang-3.7'
    - env: CXX_COMPILER=clang++-3.8   C_COMPILER=clang-3.8  BUILD_TYPE=Debug     QT_VERSION=571 PACKAGES='clang-3.8'
    - env: CXX_COMPILER=clang++-3.8   C_COMPILER=clang-3.8  BUILD_TYPE=Release   QT_VERSION=571 PACKAGES='clang-3.8'
    - env: CXX_COMPILER=clang++-3.9   C_COMPILER=clang-3.9  BUILD_TYPE=Debug     QT_VERSION=571 PACKAGES='clang-3.9'
    - env: CXX_COMPILER=clang++-3.9   C_COMPILER=clang-3.9  BUILD_TYPE=Release   QT_VERSION=571 PACKAGES='clang-3.9'

    - os: osx
      osx_image: xcode8.2
      env: BUILD_TYPE=Release
    - os: osx
      osx_image: xcode8.1
      env: BUILD_TYPE=Debug
    - os: osx
      osx_image: xcode8.1
      env: BUILD_TYPE=Release
    - os: osx
      osx_image: xcode8
      env: BUILD_TYPE=Debug
    - os: osx
      osx_image: xcode8
      env: BUILD_TYPE=Release
    - os: osx
      osx_image: xcode7.3
      env: BUILD_TYPE=Debug
    - os: osx
      osx_image: xcode7.3
      env: BUILD_TYPE=Release

install: 
  - 'if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update && sudo apt-get install $PACKAGES qt${QT_VERSION:0:2}base qt${QT_VERSION:0:2}script qt${QT_VERSION:0:2}declarative qt${QT_VERSION:0:2}tools qt${QT_VERSION:0:2}x11extras qt${QT_VERSION:0:2}svg ninja-build libedit-dev libxcb-keysyms1-dev libxml2-utils libudev-dev build-essential && source /opt/qt${QT_VERSION:0:2}/bin/qt${QT_VERSION:0:2}-env.sh; fi'
  - ./.travis/install.sh

script:
  - ./.travis/build.sh
